### PR TITLE
yml parameter added (1)

### PR DESCRIPTION
**Pull request by Justman10000**
I added yml parameters, since you can't translate without them!

### CODE REVIEW

**Comment by SychO9** [comment]
I'm confused 😅 ??
what's changed here ? I only see a dist file change which those shouldn't be committed

**Comment by Justman10000** [comment]
> 
> 
> I'm confused 😅 ??
> what's changed here ? I only see a dist file change which those shouldn't be committed

Well, I extended _afrux-theme-base.admin.extensions_ because I had translated this, because a parameter was always in English!

**Comment by SychO9** [comment]
sorry, I still do not understand

**Comment by Justman10000** [comment]
> 
> 
> sorry, I still do not understand

So... you can rewrite en.yml to translate everything, for example into German! One parameter, however, always remained in English, as this parameter was missing in the admin.js! I would suggest you just take this! I have already tested the changes and can say that it works!

**Comment by SychO9** [comment]
> > sorry, I still do not understand
> 
> So... you can rewrite en.yml to translate everything, for example into German! One parameter, however, always remained in English, as this parameter was missing in the admin.js! I would suggest you just take this! I have already tested the changes and can say that it works!

You need to commit the changed uncompiled JS files though, not the dist files, those are generated automatically, also can you do everything in a single PR ? otherwise it's hard to see changes.

**Comment by Justman10000** [comment]
> 
> 
> > > sorry, I still do not understand
> > 
> > 
> > So... you can rewrite en.yml to translate everything, for example into German! One parameter, however, always remained in English, as this parameter was missing in the admin.js! I would suggest you just take this! I have already tested the changes and can say that it works!
> 
> You need to commit the changed uncompiled JS files though, not the dist files, those are generated automatically, also can you do everything in a single PR ? otherwise it's hard to see changes.

How can I compile this?

**Pull request closed without merging**
